"""create users table

Revision ID: 19b028c49a47
Revises: cd7abf53bd15
Create Date: 2026-09-19 10:29:50.467330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b028c49a47'
down_revision: Union[str, Sequence[str], None] = 'cd7abf53bd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID user'),
    sa.Column('merchant_id', sa.UUID(), nullable=False, comment='Foreign key ke merchants.id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama lengkap user'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email user untuk login (unik)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hash password user'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Role user (owner, staff)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Status aktif user'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat user dibuat'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat user diperbarui'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_merchant_id'), 'users', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_merchant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
