"""create inventory movements table

Revision ID: 66b9ddb718bc
Revises: a1c7bf0293b9
Create Date: 2026-10-08 09:08:29.167218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b9ddb718bc'
down_revision: Union[str, Sequence[str], None] = 'a1c7bf0293b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID inventory movement'),
    sa.Column('merchant_id', sa.UUID(), nullable=False, comment='Foreign key ke merchants.id'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Foreign key ke products.id'),
    sa.Column('movement_type', sa.String(length=50), nullable=False, comment='Jenis pergerakan stok'),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False, comment='Jumlah perubahan stok'),
    sa.Column('stock_before', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False, comment='Stok sebelum perubahan'),
    sa.Column('stock_after', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False, comment='Stok setelah perubahan'),
    sa.Column('reference_type', sa.String(length=50), nullable=True, comment='Jenis sumber perubahan stok'),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='ID sumber perubahan stok tanpa foreign key'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Catatan perubahan stok'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat inventory movement dibuat'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_merchant_id'), 'inventory_movements', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_merchant_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    # ### end Alembic commands ###
