"""create products table

Revision ID: 680890a79138
Revises: b9e576f64937
Create Date: 2026-10-01 13:46:24.752914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680890a79138'
down_revision: Union[str, Sequence[str], None] = 'b9e576f64937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID product'),
    sa.Column('merchant_id', sa.UUID(), nullable=False, comment='Foreign key ke merchants.id'),
    sa.Column('category_id', sa.UUID(), nullable=False, comment='Foreign key ke categories.id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama produk'),
    sa.Column('sku', sa.String(length=100), nullable=False, comment='Stock Keeping Unit produk'),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False, comment='Harga jual produk'),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=False, comment='Harga modal produk'),
    sa.Column('stock', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False, comment='Stok produk saat ini'),
    sa.Column('unit', sa.String(length=50), nullable=False, comment='Satuan produk, misalnya pcs, kg, liter'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Status aktif produk'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat produk dibuat'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat produk diperbarui'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'sku', name='uq_products_merchant_id_sku')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_merchant_id'), 'products', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_merchant_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
