"""create customers table

Revision ID: 778b470dab95
Revises: 680890a79138
Create Date: 2026-10-01 14:02:55.491118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778b470dab95'
down_revision: Union[str, Sequence[str], None] = '680890a79138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID customer'),
    sa.Column('merchant_id', sa.UUID(), nullable=False, comment='Foreign key ke merchants.id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama customer'),
    sa.Column('phone', sa.String(length=50), nullable=False, comment='Nomor telepon customer'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Alamat email customer (opsional)'),
    sa.Column('member_code', sa.String(length=100), nullable=False, comment='Kode member customer'),
    sa.Column('address', sa.Text(), nullable=True, comment='Alamat customer (opsional)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Status aktif customer'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat customer dibuat'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat customer diperbarui'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'member_code', name='uq_customers_merchant_id_member_code')
    )
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
