"""create transaction items table

Revision ID: a1c7bf0293b9
Revises: ada96da0c868
Create Date: 2026-10-06 12:56:06.265728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c7bf0293b9'
down_revision: Union[str, Sequence[str], None] = 'ada96da0c868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID transaction item'),
    sa.Column('transaction_id', sa.UUID(), nullable=False, comment='Foreign key ke transactions.id'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Foreign key ke products.id'),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False, comment='Jumlah produk yang dibeli'),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False, comment='Harga produk saat transaksi'),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False, comment='Jumlah diskon untuk item'),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False, comment='Subtotal item setelah diskon'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat item transaksi dibuat'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat item transaksi diperbarui'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_items_product_id'), 'transaction_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_transaction_items_transaction_id'), 'transaction_items', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_items_transaction_id'), table_name='transaction_items')
    op.drop_index(op.f('ix_transaction_items_product_id'), table_name='transaction_items')
    op.drop_table('transaction_items')
    # ### end Alembic commands ###
