"""create transactions table

Revision ID: ada96da0c868
Revises: 778b470dab95
Create Date: 2026-10-01 14:29:14.300349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada96da0c868'
down_revision: Union[str, Sequence[str], None] = '778b470dab95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID transaction'),
    sa.Column('merchant_id', sa.UUID(), nullable=False, comment='Foreign key ke merchants.id'),
    sa.Column('customer_id', sa.UUID(), nullable=True, comment='Foreign key ke customers.id (opsional)'),
    sa.Column('transaction_number', sa.String(length=100), nullable=False, comment='Nomor transaksi'),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Tanggal dan waktu transaksi'),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False, comment='Subtotal transaksi sebelum diskon dan pajak'),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False, comment='Jumlah diskon transaksi'),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False, comment='Jumlah pajak transaksi'),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False, comment='Total akhir transaksi'),
    sa.Column('payment_method', sa.String(length=50), nullable=False, comment='Metode pembayaran'),
    sa.Column('payment_status', sa.String(length=50), server_default='pending', nullable=False, comment='Status pembayaran'),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False, comment='Status transaksi'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Catatan transaksi (opsional)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat transaksi dibuat'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat transaksi diperbarui'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'transaction_number', name='uq_transactions_merchant_id_transaction_number')
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
