"""create categories table

Revision ID: b9e576f64937
Revises: 19b028c49a47
Create Date: 2026-09-19 12:04:45.839068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e576f64937'
down_revision: Union[str, Sequence[str], None] = '19b028c49a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID category'),
    sa.Column('merchant_id', sa.UUID(), nullable=False, comment='Foreign key ke merchants.id'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nama kategori produk'),
    sa.Column('description', sa.Text(), nullable=True, comment='Deskripsi kategori produk (opsional)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Status aktif kategori'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat kategori dibuat'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat kategori diperbarui'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'name', name='uq_categories_merchant_id_name')
    )
    op.create_index(op.f('ix_categories_merchant_id'), 'categories', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_merchant_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
