"""create merchants table

Revision ID: cd7abf53bd15
Revises: 
Create Date: 2026-09-19 10:21:24.960685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7abf53bd15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID merchant'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama merchant'),
    sa.Column('business_type', sa.String(length=100), nullable=False, comment='Jenis usaha merchant'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Nomor telepon merchant (opsional)'),
    sa.Column('address', sa.Text(), nullable=True, comment='Alamat merchant (opsional)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat merchant dibuat'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp saat merchant diperbarui'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchants')
    # ### end Alembic commands ###
